npm install --global gulp-cli &&
npm install hexo --save &&
npm install gulp --save &&
npm install gulp-clean-css --save &&
npm install gulp-htmlclean --save &&
npm install gulp-htmlmin --save &&
npm install gulp-imagemin --save &&
npm install gulp-uglify --save &&
npm install hexo-algolia --save &&
npm install hexo-deployer-git --save &&
#npm install hexo-filter-emoji --save &&
#npm install hexo-filter-optimize --save &&
npm install hexo-generator-archive --save &&
npm install hexo-generator-baidu-sitemap --save &&
#npm install hexo-generator-category --save &&
npm install hexo-generator-feed --save &&
npm install hexo-generator-index --save &&
npm install hexo-generator-searchdb --save &&
npm install hexo-generator-tag --save &&
npm install hexo-generator-sitemap --save &&
npm install hexo-leancloud-counter-security --save &&
npm install hexo-renderer-ejs --save &&
npm install hexo-renderer-marked --save &&
npm install hexo-renderer-stylus --save &&
npm install hexo-server --save &&
npm install hexo-symbols-count-time --save &&
npm install hexo-asset-image --save &&

git clone https://github.com/theme-next/theme-next-algolia-instant-search themes/next/source/lib/algolia-instant-search &&
#git clone https://github.com/theme-next/theme-next-three themes/next/source/lib/three &&
git clone https://github.com/theme-next/theme-next-reading-progress themes/next/source/lib/reading_progress &&
git clone https://github.com/theme-next/theme-next-bookmark themes/next/source/lib/bookmark &&
#git clone https://github.com/theme-next/theme-next-pdf themes/next/source/lib/pdf &&
git clone https://github.com/theme-next/theme-next-fancybox3 themes/next/source/lib/fancybox &&
git clone https://github.com/theme-next/theme-next-quicklink themes/next/source/lib/quicklink &&
git clone https://github.com/theme-next/theme-next-fastclick themes/next/source/lib/fastclick &&
git clone https://github.com/theme-next/theme-next-pangu themes/next/source/lib/pangu &&
git clone https://github.com/theme-next/theme-next-jquery-lazyload themes/next/source/lib/jquery_lazyload &&
git clone https://github.com/theme-next/theme-next-pace themes/next/source/lib/pace &&
#git clone https://github.com/theme-next/theme-next-canvas-ribbon themes/next/source/lib/canvas-ribbon &&
#git clone https://github.com/theme-next/theme-next-canvas-nest themes/next/source/lib/canvas-nest &&
#git clone https://github.com/theme-next/theme-next-needmoreshare2 themes/next/source/lib/needsharebutton &&
git clone https://github.com/theme-next/theme-next-han themes/next/source/lib/Han